### ISSUE TITLE
If you customize the export directory, you will not be able to import `Prisma` properly

### ISSUE THREAD

**Issue by BetterLuke** [unlight/prisma-graphql-type-decimal#1]
Hi, Bro， If I customize the output directory on the schema file.
```
generator client {
  provider      = "prisma-client-js"
  output        = "../generated/prisma-client"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

```
After that, this file will state that prisma could not be found:

![image](https://user-images.githubusercontent.com/12392903/124371850-6ca86300-dcb8-11eb-8b86-212a369771ce.png)

![image](https://user-images.githubusercontent.com/12392903/124371855-7205ad80-dcb8-11eb-973b-cfa8f0fd8908.png)

I'd like to avoid this mistake for this situation, and I'd appreciate any helpful suggestions

**Comment by unlight** [comment]
Do you use it with prisma-nestjs-graphql generator?

**Comment by BetterLuke** [comment]
> Do you use it with prisma-nestjs-graphql generator?

Yes, I did it.

**Comment by unlight** [comment]
1. You need to create a reference absolute path alias to your custom `generated/prisma-client` folder, it can be done by [typescript path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping)

2. Second, you need apply [Custom @PropertyType() decorator](https://github.com/unlight/prisma-nestjs-graphql#propertytype) to all your decimals, main setting value is `from: 'generated/prisma-client'` it should reference to absolute path in step 1. Path should be absolute, because prisma-nestjs-graphql can generates files in many folders on different level, relative path may not work, unless you configure prisma-nestjs-graphql such way that all files will be stored in one folder.

**Comment by BetterLuke** [comment]
> 1. typescript path mapping

Sincere thanks. You save me a day
